### ISSUE TITLE
bug: griffe-pydantic doesn't support subclassed pydantic models

### ISSUE THREAD

**Issue by Benjamin-T** [mkdocstrings/griffe-pydantic#3]
### Description of the bug
When the class which is to be rendered as a pydantic model is not directly inheriting from `pydantic.BaseModel` the rendering fails

### To Reproduce
```python
# other file content:
from pydantic.main import BaseModel


class InheritedBaseModel(BaseModel):
    """"""
```

When trying to render the example model:

```python
from other_file import InheritedBaseModel

class ExampleModel(InheritedBaseModel):
    """An example model."""

    model_config = ConfigDict(frozen=False)

    field_without_default: str
    """Shows the *[Required]* marker in the signature."""

    field_plain_with_validator: int = 100
    """Show standard field with type annotation."""

    field_with_validator_and_alias: str = Field("FooBar", alias="BarFoo", validation_alias="BarFoo")
    """Shows corresponding validator with link/anchor."""

    field_with_constraints_and_description: int = Field(
        default=5, ge=0, le=100, description="Shows constraints within doc string."
    )

    @field_validator("field_with_validator_and_alias", "field_without_default")
    @classmethod
    def check_max_length_ten(cls, v) -> str:
        """Show corresponding field with link/anchor."""
        if len(v) >= 10:
            raise ValueError("No more than 10 characters allowed")
        return v

```

Using these mkdocs.yml settings:

```yaml
site_name: "My Library"

theme:
  name: "material"

plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [.]
        options:
          extensions:
          - griffe_pydantic:
              schema: true
```

```console
$ mkdocs serve
INFO    -  Building documentation...
INFO    -  Cleaning site directory
INFO    -  mkdocstrings_handlers: .conda\Lib\site-packages\griffe_pydantic\templates\material\pydantic_model.html: DeprecationWarning: Extending '_base/class.html' is deprecated, extend '_base/class.html.jinja'           instead. After some time, this message will be logged as a warning, causing strict builds to fail.
INFO    -  Documentation built in 0.91 seconds
INFO    -  [20:39:57] Watching paths for changes: 'docs', 'mkdocs.yml'
INFO    -  [20:39:57] Serving on http://127.0.0.1:8000/
```

### Expected behavior
I expect the model to render just fine.

### Environment information

```toml
[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.7.1"
griffe = "0.45.2"
mkdocs = "^1.6.0"
mkdocs-material = "^9.5.24"
mkdocstrings = "^0.25.1"
mkdocstrings-python = "^1.10.3"
ruamel-yaml = "^0.18.6"
pydantic-yaml = "^1.3.0"
```

### Additional context
The result:
![image](https://github.com/mkdocstrings/griffe/assets/20844540/810fe9f6-e543-4139-9258-d87b208c551a)

When the `InheritedBaseModel` is replaced with the `pydantic.BaseModel` the result is as expected:
![image](https://github.com/mkdocstrings/griffe/assets/20844540/5cb66541-a51a-497b-83bc-ea39550a65c4)
