### ISSUE TITLE
bug:

### ISSUE THREAD

**Issue by N1k145** [mkdocstrings/griffe-pydantic#35]
### Description of the bug

In the example on the index page of the documentation [here](https://mkdocstrings.github.io/griffe-pydantic/#model_ext.ExampleModel.field_with_constraints_and_description) I understand this as that the contraints should be part of the documentation
```python
    field_with_constraints_and_description: int = Field(
        default=5, ge=0, le=100, description="Shows constraints within doc string."
    )
```
![Image](https://github.com/user-attachments/assets/72181f68-5999-4419-a629-6a75f14407ac)

But for me this is only the default value and I am unable to get other contraints to work, like the max-length of a string

### To Reproduce

```python
class ModelElement(BaseModel):
    name: str = Field(max_length=255)
    """The name of the model element"""
```

### Expected behavior
I would like to see the contrains as part of the documentation

### Environment information

- __System__: Windows-11-10.0.22631-SP0
- __Python__: cpython 3.13.3 (D:\[...]\.venv\Scripts\python.exe)
- __Environment variables__:
- __Installed packages__:
  - `griffe-pydantic` v1.1.4

### Additional context
Im running it directly as an mkdocs-extension with the same setup as in this repo
```
                    options:
                        docstring_options:
                            ignore_init_summary: true
                        docstring_section_style: list
                        filters: [ "!^_" ]
                        heading_level: 1
                        inherited_members: true
                        merge_init_into_class: true
                        separate_signature: true
                        show_root_heading: true
                        show_root_full_path: false
                        show_signature_annotations: true
                        show_source: false
                        show_symbol_type_heading: true
                        show_symbol_type_toc: true
                        signature_crossrefs: true
                        summary: true
                        extensions:
                            -   griffe_pydantic:
                                    schema: true
```
