### ISSUE TITLE
bug: Extension does not work when `separate_signature` is set to True [mkdocs]

### ISSUE THREAD

**Issue by mmzeynalli** [mkdocstrings/griffe-pydantic#9]
### Description of the bug

So, I had my docs already working. Added new pydantic models and saw that mkdocstrings cannot parse it correctly so I used this extension, but got really similar result. 

### To Reproduce

My config file:

```
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../../src]
          options:
            show_root_heading: true
            show_source: false
            show_if_no_docstring: true
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            filters:
            - '!^_'
            merge_init_into_class: true
            docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            extensions:
            - griffe_pydantic
```

### Full traceback

<details><summary>Full traceback</summary>

```python
PASTE TRACEBACK HERE
```

</details>

### Current behavior

The docstrings of fields are shown okay, however, it does not show the types of fields.

![image](https://github.com/user-attachments/assets/8f9d15be-47d5-4ef4-8252-78aa5abf1560)

### Expected behavior

If I comment out `separate_signature: true`, then everything is as expected:

![image](https://github.com/user-attachments/assets/0367b5a6-0441-4b36-b0ed-a827359595c8)
 

### Environment information

```bash
- __System__: Linux-6.8.0-1014-oem-x86_64-with-glibc2.39
- __Python__: cpython 3.12.3
- __Environment variables__:
- __Installed packages__:
  - `griffe-pydantic` v1.0.0
```
